spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password: '{cipher}AQBsnpA5n/YDd5royhIj994ol9kk/8EEa5xznD6tvCSm+WW7oMdqyLvtUzHkIdVM/wrBLiTUS1TN8S47sJS7pGW3okA6oV1CcSTjCjZZdq9EKIMA5sxcXDGhIL1i7L+SJ+EXicElSHQhlWpefPU9fO7XyUvW9xWNy+F5Gpp4481dun1PAsVdwgJbju76rYgolKm9PMNk5gRPtfX/EPwrYfRY4QUwiWXdRDQ8pHlq3ltmekV0K5gg+dWi0u4fj2ACFNZxgpvQzzy6CdjKAQ7rzafkhdwqIGTnfUOk4/7cXe6S7oJBe//oFwLdek7Z9SbBAQTIbSS1eSbdimzjPom0XS26keTNq39maZYHB72LY3U7HCcBJpAYIJ+NTKNdayI944c='

token:
  expiration-time: 86400000
  secret: '{cipher}AQBErp4pc/lD+hVfjU1bAX17v0+uEAxThDbIQSfdFS2XMI6EVxeAlvYQYRtZ5t6DgU32xYi16tHA4a/qvT+3tMRBXk+HcBJcN9cm8Cq3KpxpsWQwtTkznZPg7JEyTcSTqP+V0BwBYYSanHnlg/9j+Z/ziCsbDSaVgLcwGq5dB/jE2ZRFIO0vTstDmi15zx96z/DHiMl1vFN65bvsVEwlht6dYgsyLlOLgb9wLlzI3vcEPdsglaNAaHEE/UbkFu8RrG5pMzSn38sAHIeE+6zWR4wV0fPLZjvBR70dk/jxS8AKdUk2XUligLX5ENKzX3IG5SuDj0EXW/XcVRmaVUrh4MYOICrddehuiREQj7uqi6RVj7sRWVDRsMuZ9iTfZ1nXkorWHaScmgdrOnH5zj/+O8KCM2nyXNyT7vdAMUFIE+Hofg=='
  
gateway:
  ip: 192.168.0.108 