spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password: '{cipher}01a5920c8e00ac5d817706e86bfb9c1bf1ab6805c640856094b3c4837fbb6971'
    
token:
  expiration-time: 86400000
  secret: user_token_taehyun_key_jjazengnanda_taehyun_prod2
  
gateway:
  ip: 192.168.0.108 